abstract class AppStrings {
  static String myoreders = "My Orders",
      ongoing = 'Ongoing',
      history = 'History',
      trackOrder = 'Track Order',
      cancel = 'Cancel',
      completed = 'Completed',
      rate = 'Rate',
      reOrder = 'Re-Order',
      profile = 'Profile',
      ilovefastfood = 'I love fast food',
      personalInfo = 'Personal Info',
      addresses = 'Addresses',
      cart = 'Cart',
      favourite = 'Favourite',
      notifications = 'Notifications',
      paymentMethod = 'Payment Method',
      fAQs = 'FAQs',
      userReviews = ' User Reviews',
      settings = 'Settings',
      logOut = 'Log Out',
      fullName = 'Full Name',
      email = 'Email',
      phoneNumber = 'Phone Number',
      bio = 'Bio',
      editProfile = 'Edit Profile',
      edit = 'EDIT';
}
